const bankSelect = [
	{
		Label: "กระบวนการตรวจสอบความถูกต้องของหนังสือรับรอง",
		Value: "ddd",
	},
	{
		Label: "กระบวนการพิมพ์ซ่อม",
		Value: "digitallySign",
	},
	{
		Label: "กระบวนการร้องขอพิมพ์ซ่อม",
		Value: "sendToBanks",
	},
]

export const printoutPrimary = {
	Name: "printoutPrimary",
	Description: "",
	Action: "/",
	Method: "post",
	Inputs: [
		{
			Name: "masterFile",
			Label: "ไฟล์",
			Type: "File",
			Description: "",
			Required: true,
			Accept: "application/pdf",
		},
		{
			Name: "certificateContextName",
			Label: "ระบบที่รับรอง",
			Description: "",
			Type: "Text",
			Required: true,
			MaxLength: 140,
			Placeholder: "ชื่อของคอร์สที่รองรับ",
		},
		{
			Name: "receiverName",
			Label: "หน่วยงานผู้รับใบรับรอง",
			Description: "",
			Type: "Text",
			MaxLength: 256,
			Placeholder: "ชื่อบุคคลผู้รับใบรับรอง",
			Required: true,
		},
		{
			Name: "receiverId",
			Label: "เลขทะเบียนนิติบุคคลผู้รับใบรับรอง",
			MaxLength: 35,
			Description: "",
			Type: "Text",
			Placeholder: "เลขบัตรประจำตัวประชาชนของผู้รับใบรับรอง",
			Required: false,
		},
		{
			Name: "certificateContextId",
			Label: "เลขที่หนังสือรับรอง",
			MaxLength: 35,
			Description: "",
			Type: "Text",
			Placeholder: "เลขที่หนังสืออ้างอิง",
			Required: true,
		},
		{
			Name: "certificateContextFirstIssueDateTime",
			Label: "วันที่ออกหนังสือรับรองครั้งแรก",
			MaxLength: 35,
			Description: "",
			Type: "DateTime",
			Required: true,
		},
		{
			Name: "certificateContextIssueDateTime",
			Label: "วันที่ออกหนังสือรับรองครั้งล่าสุด",
			MaxLength: 35,
			Description: "",
			Type: "Date",
			Required: true,
		},
		{
			Name: "certificateContextExpireDateTime",
			Label: "วันที่หนังสือรับรองหมดอายุ",
			MaxLength: 35,
			Description: "",
			Type: "Date",
			Required: true,
		},
		{
			Name: "receiverAddressLineOne",
			Label: "ที่อยู่หน่วยงานผู้รับใบรับรอง",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: true,
		},
		{
			Name: "receiverAddressLineTwo",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverAddressLineThree",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverAddressLineFour",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverAddressLineFive",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "certifiedDetailReceiverSite",
			Label: "สถานที่/พื้นที่ในการรับรอง",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverSiteAddressLineOne",
			Label: "ที่อยู่หน่วยงานผู้รับใบรับรอง",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: true,
		},
		{
			Name: "receiverSiteAddressLineTwo",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverSiteAddressLineThree",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverSiteAddressLineFour",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "receiverSiteAddressLineFive",
			Label: "",
			MaxLength: 140,
			Description: "",
			Type: "Text",
			Required: false,
		},
		{
			Name: "contentTypeCode",
			Label: "กระบวนการ/กิจกรรม ของ สถานที่/พื้นที่การรับรอง",
			Description: "",
			Type: "Select",
			Items: [
				{
					Label: "กระบวนการสร้างไฟล์หนังสือรับรอง",
					Value: "certifiedFile",
				},
				{
					Label: "กระบวนการลงนามหนังสือรับรองด้วย Digital Signature",
					Value: "digitallySign",
				},
				{
					Label: "กระบวนการส่งไฟล์หนังสือรับรองให้ธนาคาร",
					Value: "sendToBanks",
				},
			],
			Required: true,
		},
		{
			Name: "bankBBL",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารกรุงเทพ จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankKTB",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารกรุงไทย จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankGSB",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารออมสิน",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankKBANK",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารกสิกรไทย จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankSCB",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารไทยพานิชย์ จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankMIZUHO",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารมิซูโฮ จำกัด",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankTBANK",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารธนชาติ จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankBAY",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารกรุงศรีอยุธยา จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankKK",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารเกียรตินาคิน จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		{
			Name: "bankTMB",
			Label: "กระบวนการ/กิจกรรม ของ ธนาคารทหารไทย จำกัด (มหาชน)",
			MaxLength: 140,
			Description: "",
			Type: "Checkbox",
			Items: bankSelect,
			Required: true,
		},
		
	],
	ActionButtons: [
		{
			Type: "primary",
			Action: "submit",
			Content: "บันทึกข้อมูล",
			Disabled: false,
		},
		{
			Type: "secondary",
			Action: "reset",
			Content: "ยกเลิก",
			Disabled: false,
		},
	],
};